/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package berlinclock;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;

/**
 *
 * @author Komal
 */
public class berlinclockUI extends javax.swing.JFrame {

    /**
     * Creates new form berlinclockUI
     */
    String s = null;
      Color yellow =Clock.Clock_Color.YELLOW.getValue();
      Color red =Clock.Clock_Color.RED.getValue();
      Color gray =Clock.Clock_Color.GRAY.getValue();       
    public berlinclockUI() {
        initComponents();

    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        time = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        forth = new javax.swing.JLabel();
        first = new javax.swing.JLabel();
        second = new javax.swing.JLabel();
        third = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BerlinClock");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel1.setLayout(null);
        jPanel1.add(time);
        time.setBounds(30, 40, 98, 30);

        jButton1.setText("Result");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 90, 63, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("sec");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(300, 50, 70, 30);

        jLabel4.setText("Enter Time");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 20, 80, 14);

        forth.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        forth.setText("forth");
        jPanel1.add(forth);
        forth.setBounds(280, 180, 140, 20);

        first.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        first.setText("first");
        jPanel1.add(first);
        first.setBounds(280, 90, 150, 20);

        second.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        second.setText("second");
        jPanel1.add(second);
        second.setBounds(280, 120, 150, 20);

        third.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        third.setText("third");
        jPanel1.add(third);
        third.setBounds(280, 150, 170, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        s = time.getText();

        Berlin bp = new Berlin();
        bp.setTime(s);
        BerlinClock bclock = new BerlinClock();
        String output = bclock.berlinClockDecode(s);
        System.out.println(output);
      
            
        
        jLabel1.setText(output.substring(0,1));        
        if(jLabel1.getText().equals("Y")){
            jLabel1.setForeground(yellow);
        }else{
            jLabel1.setForeground(gray);
        }
        
        first.setText(output.substring(1,6));
        second.setText(output.substring(6, 11));
        third.setText(output.substring(11, 22));
        forth.setText(output.substring(22));
      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(berlinclockUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(berlinclockUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(berlinclockUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(berlinclockUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new berlinclockUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel first;
    private javax.swing.JLabel forth;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel second;
    private javax.swing.JLabel third;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables
}
